#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MICROPIXEL_FONT_CBIN_MAGIC "MPXFCBN\0"
#define MICROPIXEL_FONT_CBIN_MAGIC_SIZE 8U
#define MICROPIXEL_FONT_CBIN_HEADER_VERSION 1U
#define MICROPIXEL_FONT_CBIN_HEADER_SIZE 160U
#define MICROPIXEL_FONT_CBIN_FORMAT_LVGL_V1 1U
#define MICROPIXEL_FONT_CBIN_ENDIAN_LITTLE 1U
#define MICROPIXEL_FONT_CBIN_POINTER_SIZE 4U
#define MICROPIXEL_FONT_CBIN_GLYPH_DSC_LARGE 1U
#define MICROPIXEL_FONT_CBIN_SHA256_SIZE 32U
#define MICROPIXEL_FONT_CBIN_CONVERTER_COMMIT_SIZE 20U
#define MICROPIXEL_FONT_CBIN_PROFILE_SIZE 32U

// Wire offsets in MicropixelFontCbinHeader v1. The header is decoded field by
// field; it is never cast to a native struct.
#define MICROPIXEL_FONT_CBIN_OFFSET_HEADER_VERSION 8U
#define MICROPIXEL_FONT_CBIN_OFFSET_HEADER_SIZE 10U
#define MICROPIXEL_FONT_CBIN_OFFSET_TOTAL_SIZE 12U
#define MICROPIXEL_FONT_CBIN_OFFSET_PAYLOAD_OFFSET 16U
#define MICROPIXEL_FONT_CBIN_OFFSET_PAYLOAD_SIZE 20U
#define MICROPIXEL_FONT_CBIN_OFFSET_FORMAT 24U
#define MICROPIXEL_FONT_CBIN_OFFSET_LVGL_MAJOR 28U
#define MICROPIXEL_FONT_CBIN_OFFSET_LVGL_MINOR 30U
#define MICROPIXEL_FONT_CBIN_OFFSET_LVGL_PATCH 32U
#define MICROPIXEL_FONT_CBIN_OFFSET_ENDIAN 34U
#define MICROPIXEL_FONT_CBIN_OFFSET_POINTER_SIZE 35U
#define MICROPIXEL_FONT_CBIN_OFFSET_GLYPH_DSC_LAYOUT 36U
#define MICROPIXEL_FONT_CBIN_OFFSET_FLAGS 37U
#define MICROPIXEL_FONT_CBIN_OFFSET_FONT_SIZE_PX 38U
#define MICROPIXEL_FONT_CBIN_OFFSET_CONVERTER_COMMIT 40U
#define MICROPIXEL_FONT_CBIN_OFFSET_PROFILE 60U
#define MICROPIXEL_FONT_CBIN_OFFSET_CHARSET_SHA256 92U
#define MICROPIXEL_FONT_CBIN_OFFSET_PAYLOAD_SHA256 124U
#define MICROPIXEL_FONT_CBIN_OFFSET_RESERVED1 156U

#ifdef __cplusplus
}
#endif
