#!/usr/bin/env python3
"""Generate fixed-size Wi-Fi status masks from LVGL's built-in Wi-Fi glyph."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


GLYPH = "\uf1eb"
FONT_SIZE = 16


def render_source(font_path: Path) -> Image.Image:
    font = ImageFont.truetype(str(font_path), FONT_SIZE)
    left, top, right, bottom = font.getbbox(GLYPH)
    image = Image.new("L", (right - left, bottom - top), 0)
    ImageDraw.Draw(image).text((-left, -top), GLYPH, font=font, fill=255)
    return image


def clear_rows(image: Image.Image, end: int) -> Image.Image:
    result = image.copy()
    ImageDraw.Draw(result).rectangle((0, 0, result.width, end - 1), fill=0)
    return result


def make_medium(source: Image.Image) -> Image.Image:
    result = clear_rows(source, 6)
    # Row 6 contains both the last two pixels of the outer arc and the
    # anti-aliased crown of the inner arc. Remove only the outer remnants so
    # the medium-strength arc keeps its rounded top.
    draw = ImageDraw.Draw(result)
    draw.rectangle((0, 6, 4, 6), fill=0)
    draw.rectangle((15, 6, result.width - 1, 6), fill=0)
    return result


def c_bytes(image: Image.Image) -> str:
    values = image.tobytes()
    rows = []
    for offset in range(0, len(values), 12):
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in values[offset : offset + 12]) + ",")
    return "\n".join(rows)


def descriptor(name: str, image: Image.Image) -> str:
    return f"""const lv_image_dsc_t {name} = {{
    .header.cf = LV_COLOR_FORMAT_A8,
    .header.w = {image.width},
    .header.h = {image.height},
    .header.stride = {image.width},
    .data_size = sizeof({name}_map),
    .data = {name}_map,
}};"""


def generate(font_path: Path, output: Path) -> None:
    full = render_source(font_path)
    variants = {
        "micropixel_wifi_status_weak": clear_rows(full, 11),
        "micropixel_wifi_status_medium": make_medium(full),
        "micropixel_wifi_status_full": full,
    }
    sections = [
        "// clang-format off: generated by tools/generate_wifi_status_icons.py",
        '#include "lvgl.h"',
        "",
    ]
    for name, image in variants.items():
        sections.extend(
            [
                f"static const uint8_t {name}_map[] = {{",
                c_bytes(image),
                "};",
                "",
                descriptor(name, image),
                "",
            ]
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(sections), encoding="utf-8")


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    default_font = (
        repo_root
        / "firmware/espressif/managed_components/lvgl__lvgl/scripts/built_in_font/FontAwesome5-Solid+Brands+Regular.woff"
    )
    default_output = (
        repo_root / "firmware/espressif/main/platform/lvgl/ui/square_common/icons/wifi_status_icons.c"
    )
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", type=Path, default=default_font)
    parser.add_argument("--output", type=Path, default=default_output)
    args = parser.parse_args()
    generate(args.font, args.output)


if __name__ == "__main__":
    main()
