#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Derive cellular status masks and a preview from Font Awesome's signal glyph.

Use --preview for visual inspection and --output for generated LVGL A8 C data.
Keep generated files outside the source tree.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

import generate_wifi_status_icons as wifi


GLYPH = "\uf012"


def render_source(font_path: Path) -> Image.Image:
    font = ImageFont.truetype(str(font_path), wifi.FONT_SIZE)
    left, top, right, bottom = font.getbbox(GLYPH)
    image = Image.new("L", (right - left, bottom - top), 0)
    ImageDraw.Draw(image).text((-left, -top), GLYPH, font=font, fill=255)
    return image


def variants(source: Image.Image) -> list[Image.Image]:
    # Find transparent gaps rather than cutting through anti-aliased edges.
    ends = []
    occupied = False
    for x in range(source.width + 1):
        current = x < source.width and source.crop((x, 0, x + 1, source.height)).getbbox() is not None
        if occupied and not current:
            ends.append(x)
        occupied = current
    if len(ends) != 5:
        raise ValueError(f"Expected five separated signal bars, found {len(ends)}")
    result = []
    for end in ends:
        image = source.copy()
        if end < source.width:
            ImageDraw.Draw(image).rectangle((end, 0, source.width - 1, source.height - 1), fill=0)
        result.append(image)
    return result


def write_c(images: list[Image.Image], output: Path) -> None:
    sections = [
        "// clang-format off: generated by tools/generate_cellular_status_icons.py",
        '#include "lvgl.h"',
        "",
    ]
    for level, image in enumerate(images, 1):
        name = f"micropixel_cellular_status_{level}"
        sections.extend([
            f"static const uint8_t {name}_map[] = {{",
            wifi.c_bytes(image),
            "};",
            "",
            wifi.descriptor(name, image),
            "",
        ])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(sections), encoding="utf-8")


def preview(images: list[Image.Image], font_path: Path, output: Path) -> None:
    canvas = Image.new("RGB", (1000, 570), "#111827")
    draw = ImageDraw.Draw(canvas)
    heading = ImageFont.load_default(size=24)
    label = ImageFont.load_default(size=16)
    draw.text((28, 20), "Cellular signal / Font Awesome U+F012", font=heading, fill="#f3f4f6")
    draw.text((28, 57), "Original 20 x 16 mask. Unused bars are transparent; baseline and canvas stay fixed.",
              font=label, fill="#a5b4c7")
    for index, mask in enumerate(images):
        x = 30 + index * 194
        draw.text((x, 105), f"{index + 1} / 5" + ("  original" if index == 4 else ""), font=label, fill="#f3f4f6")
        enlarged = mask.resize((mask.width * 8, mask.height * 8), Image.Resampling.NEAREST)
        canvas.paste("#f3f4f6", (x, 140, x + enlarged.width, 140 + enlarged.height), enlarged)
        draw.line((x, 273, x + 160, 273), fill="#374151")
        draw.text((x, 292), "Native size", font=label, fill="#a5b4c7")
        canvas.paste("#f3f4f6", (x, 324, x + mask.width, 324 + mask.height), mask)
    draw.text((28, 386), "Existing Wi-Fi masks / same font and raster size", font=heading, fill="#f3f4f6")
    full = wifi.render_source(font_path)
    for index, (name, mask) in enumerate([
        ("Weak", wifi.clear_rows(full, 11)), ("Medium", wifi.make_medium(full)), ("Full", full)
    ]):
        x = 30 + index * 194
        enlarged = mask.resize((mask.width * 4, mask.height * 4), Image.Resampling.NEAREST)
        canvas.paste("#f3f4f6", (x, 432, x + enlarged.width, 432 + enlarged.height), enlarged)
        draw.text((x, 510), name, font=label, fill="#a5b4c7")
    output.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(output)


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", type=Path, default=root / (
        "firmware/espressif/managed_components/lvgl__lvgl/scripts/"
        "built_in_font/FontAwesome5-Solid+Brands+Regular.woff"
    ))
    parser.add_argument("--output", type=Path)
    parser.add_argument("--preview", type=Path)
    args = parser.parse_args()
    if not args.output and not args.preview:
        parser.error("provide --output and/or --preview")
    images = variants(render_source(args.font))
    if args.output:
        write_c(images, args.output)
    if args.preview:
        preview(images, args.font, args.preview)


if __name__ == "__main__":
    main()
