#ifndef MICROPIXEL_APPS_TOMB_EXPLORER_GFX_TEXTURES_HPP
#define MICROPIXEL_APPS_TOMB_EXPLORER_GFX_TEXTURES_HPP

// Generated by tools/generate_textures.py; do not edit.
#include <stdint.h>

#include <span>

namespace tomb::gfx {

constexpr uint32_t kTextureSize = 64U;

// Texture slot IDs, uploaded in this order. Level faces reference them by value.
enum TextureSlot : uint8_t {
    kTexWall = 0U,
    kTexFloor = 1U,
    kTexCeiling = 2U,
    kTexCarved = 3U,
    kTexMossyWall = 4U,
    kTexSteps = 5U,
    kTexCloth = 6U,
    kTexFace = 7U,
    kTexWater = 8U,
    kTexBone = 9U,
    kTextureCount = 10U,
};

// kRowMajor kTextureSize x kTextureSize INDEX8 texels of slot `slot`.
[[nodiscard]] std::span<const uint8_t> TextureTexels(uint8_t slot);

}  // namespace tomb::gfx

#endif
