#ifndef MICROPIXEL_RUNTIME_BUNDLEFS_BUNDLEFS_FORMAT_H
#define MICROPIXEL_RUNTIME_BUNDLEFS_BUNDLEFS_FORMAT_H

#include <stdint.h>

#define MICROPIXEL_BUNDLEFS_FORMAT_VERSION 1U
#define MICROPIXEL_BUNDLEFS_BANK_SIZE (4U * 1024U)
#define MICROPIXEL_BUNDLEFS_BANK_COUNT 4U
#define MICROPIXEL_BUNDLEFS_CATALOG_RECORD_SIZE MICROPIXEL_BUNDLEFS_BANK_SIZE
#define MICROPIXEL_BUNDLEFS_METADATA_SIZE (64U * 1024U)
#define MICROPIXEL_BUNDLEFS_DATA_OFFSET MICROPIXEL_BUNDLEFS_METADATA_SIZE
#define MICROPIXEL_BUNDLEFS_DATA_BLOCK_SIZE (64U * 1024U)
#define MICROPIXEL_BUNDLEFS_MAX_DATA_BLOCKS 383U
#define MICROPIXEL_BUNDLEFS_MAX_FILE_SIZE (8U * 1024U * 1024U)
#define MICROPIXEL_BUNDLEFS_MAX_FILE_BLOCKS (MICROPIXEL_BUNDLEFS_MAX_FILE_SIZE / MICROPIXEL_BUNDLEFS_DATA_BLOCK_SIZE)

#endif
