#!/usr/bin/env python3
"""Generate the tomb-explorer INDEX8 textures as C++ (gfx/textures.{hpp,cpp}).

Every texture is drawn procedurally from a fixed seed into the 16 ramp x 16
step palette of gfx/palette.hpp, so no source images or image libraries are
involved. Use --check to verify the checked-in C++ matches this script.
"""
import argparse
import math
import random
from pathlib import Path

APP = Path(__file__).resolve().parents[1]
SIZE = 64

RAMPS = ['gray', 'sand', 'ochre', 'brown', 'moss', 'teal', 'blue', 'gold', 'red', 'skin', 'hair', 'cloth',
         'leather', 'bone', 'water', 'white']


def index(ramp, step):
    step = max(0, min(15, int(round(step))))
    return RAMPS.index(ramp) * 16 + step


def noise_grid(rng, cells):
    return [[rng.random() for _ in range(cells)] for _ in range(cells)]


def smooth(grid, x, y):
    """Bilinear sample of a wrapping value grid at texel (x, y)."""
    cells = len(grid)
    fx = x / SIZE * cells
    fy = y / SIZE * cells
    x0, y0 = int(fx) % cells, int(fy) % cells
    x1, y1 = (x0 + 1) % cells, (y0 + 1) % cells
    tx, ty = fx - int(fx), fy - int(fy)
    top = grid[y0][x0] * (1 - tx) + grid[y0][x1] * tx
    bottom = grid[y1][x0] * (1 - tx) + grid[y1][x1] * tx
    return top * (1 - ty) + bottom * ty


def texture(fn, seed):
    rng = random.Random(seed)
    grain = noise_grid(rng, 16)
    coarse = noise_grid(rng, 4)
    texels = bytearray(SIZE * SIZE)
    for y in range(SIZE):
        for x in range(SIZE):
            texels[y * SIZE + x] = fn(x, y, rng, smooth(grain, x, y), smooth(coarse, x, y))
    return bytes(texels)


def sandstone_blocks(x, y, rng, grain, coarse):
    row = y // 16
    shift = 16 if row % 2 else 0
    bx = (x + shift) % 32
    by = y % 16
    if by < 2 or bx < 2:
        return index('brown', 3 + grain * 3)
    edge = min(bx - 2, 31 - bx, by - 2, 15 - by)
    step = 9 + coarse * 3 + grain * 2 - (1 if edge == 0 else 0)
    return index('sand', step)


def floor_slabs(x, y, rng, grain, coarse):
    bx, by = x % 32, y % 32
    if bx < 2 or by < 2:
        return index('gray', 2 + grain * 2)
    crack = abs(math.sin((x + y * 0.7) * 0.35 + coarse * 6)) < 0.03
    step = 7 + coarse * 4 + grain * 2 - (3 if crack else 0)
    return index('gray', step)


def rough_ceiling(x, y, rng, grain, coarse):
    step = 3 + coarse * 4 + grain * 3
    return index('brown', step)


def carved_band(x, y, rng, grain, coarse):
    """Decorative frieze: gold zigzag on ochre, used around doorways."""
    zig = abs((x % 16) - 8)
    if abs(y - 32) < 10 and abs(zig - (y - 22) // 2) < 2:
        return index('gold', 11 + grain * 3)
    if y < 6 or y >= 58:
        return index('brown', 4 + grain * 2)
    return index('ochre', 8 + coarse * 3 + grain * 2)


def mossy_wall(x, y, rng, grain, coarse):
    base = sandstone_blocks(x, y, rng, grain, coarse)
    moss = coarse * 0.7 + grain * 0.5
    if moss > 0.75 and y > 20:
        return index('moss', 5 + grain * 5)
    return base


def stone_steps(x, y, rng, grain, coarse):
    if y < 4:
        return index('gray', 12 + grain * 2)
    return index('gray', 5 + coarse * 3 + grain * 2)


def cloth(x, y, rng, grain, coarse):
    if 28 <= y < 36:
        return index('leather', 6 + grain * 3)
    if (x // 4 + y // 4) % 2 == 0:
        return index('cloth', 9 + grain * 2)
    return index('cloth', 8 + grain * 2)


def face(x, y, rng, grain, coarse):
    """Head: hair on top and back (upper 24 rows), face below with eyes."""
    if y < 20:
        return index('hair', 4 + grain * 4)
    if 30 <= y < 36 and (16 <= x < 24 or 40 <= x < 48):
        return index('white', 13) if (x % 8) not in (3, 4) else index('hair', 2)
    if 44 <= y < 47 and 26 <= x < 38:
        return index('red', 8)
    return index('skin', 11 + grain * 2)


def water(x, y, rng, grain, coarse):
    wave = math.sin(x * 0.3 + coarse * 4) + math.sin(y * 0.25 + grain * 3)
    return index('water', 7 + wave * 2.5)


def bone(x, y, rng, grain, coarse):
    return index('bone', 9 + coarse * 3 + grain * 2)


TEXTURES = [
    ('kTexWall', sandstone_blocks, 1),
    ('kTexFloor', floor_slabs, 2),
    ('kTexCeiling', rough_ceiling, 3),
    ('kTexCarved', carved_band, 4),
    ('kTexMossyWall', mossy_wall, 5),
    ('kTexSteps', stone_steps, 6),
    ('kTexCloth', cloth, 7),
    ('kTexFace', face, 8),
    ('kTexWater', water, 9),
    ('kTexBone', bone, 10),
]


def render_header():
    lines = [
        '#ifndef MICROPIXEL_APPS_TOMB_EXPLORER_GFX_TEXTURES_HPP',
        '#define MICROPIXEL_APPS_TOMB_EXPLORER_GFX_TEXTURES_HPP',
        '',
        '// Generated by tools/generate_textures.py; do not edit.',
        '#include <stdint.h>',
        '',
        '#include <span>',
        '',
        'namespace tomb::gfx {',
        '',
        f'constexpr uint32_t kTextureSize = {SIZE}U;',
        '',
        '// Texture slot IDs, uploaded in this order. Level faces reference them by value.',
        'enum TextureSlot : uint8_t {',
    ]
    for slot, (name, _, _) in enumerate(TEXTURES):
        lines.append(f'    {name} = {slot}U,')
    lines += [
        f'    kTextureCount = {len(TEXTURES)}U,',
        '};',
        '',
        '// kRowMajor kTextureSize x kTextureSize INDEX8 texels of slot `slot`.',
        '[[nodiscard]] std::span<const uint8_t> TextureTexels(uint8_t slot);',
        '',
        '}  // namespace tomb::gfx',
        '',
        '#endif',
        '',
    ]
    return '\n'.join(lines)


def render_source():
    lines = [
        '// Generated by tools/generate_textures.py; do not edit.',
        '#include "apps/tomb-explorer/gfx/textures.hpp"',
        '',
        'namespace tomb::gfx {',
        'namespace {',
        '',
        '// clang-format off',
    ]
    for name, fn, seed in TEXTURES:
        texels = texture(fn, seed)
        lines.append(f'constexpr uint8_t {name}Texels[kTextureSize * kTextureSize] = {{')
        for row in range(SIZE):
            values = ', '.join(str(v) for v in texels[row * SIZE:(row + 1) * SIZE])
            lines.append(f'    {values},')
        lines.append('};')
        lines.append('')
    lines.append('constexpr const uint8_t* kTextures[kTextureCount] = {')
    for name, _, _ in TEXTURES:
        lines.append(f'    {name}Texels,')
    lines += [
        '};',
        '// clang-format on',
        '',
        '}  // namespace',
        '',
        'std::span<const uint8_t> TextureTexels(uint8_t slot) {',
        '    if (slot >= kTextureCount) return {};',
        '    return {kTextures[slot], kTextureSize * kTextureSize};',
        '}',
        '',
        '}  // namespace tomb::gfx',
        '',
    ]
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='verify the generated files are up to date')
    args = parser.parse_args()
    outputs = {APP / 'gfx/textures.hpp': render_header(), APP / 'gfx/textures.cpp': render_source()}
    stale = [path for path, text in outputs.items() if not path.exists() or path.read_text() != text]
    if args.check:
        if stale:
            raise SystemExit('stale: ' + ', '.join(str(p.relative_to(APP)) for p in stale))
        print('tomb-explorer textures up to date')
        return
    for path, text in outputs.items():
        path.write_text(text)
        print(f'wrote {path.relative_to(APP)}')


if __name__ == '__main__':
    main()
